version: '3.8'

services:
  app:
    container_name: chat-agent-rag
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CHROMA_URL=http://chromadb:8000
      - GOOGLE_API_KEY=AIzaSyDfYoheEHRlf_Tr9WDZj-USQTMi4x221ns
    depends_on:
      - chromadb
    networks:
      - app-network
    restart: unless-stopped

  chromadb:
    container_name: chromadb
    image: chromadb/chroma:latest
    volumes:
      - chroma-data:/chroma/chroma
    ports:
      - "8000:8000"
    networks:
      - app-network
    restart: unless-stopped
    environment:
      - ALLOW_RESET=true
      - CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER=chromadb.auth.token.TokenAuthCredentialsProvider
      - CHROMA_SERVER_AUTH_CREDENTIALS=admin:admin
      - CHROMA_SERVER_AUTH_PROVIDER=chromadb.auth.token.TokenAuthServerProvider

networks:
  app-network:
    driver: bridge

volumes:
  chroma-data:
    driver: local 